services:
  backend:
    build:
      context: .
      target: production
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=${REDIS_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    networks:
      - app_network
    depends_on:
      - redis
      - database

  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hookcrux
      POSTGRES_USER: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app_network
    expose:
      - 5432

  redis:
    image: redis:latest
    ports:
      - '127.0.0.1:6379:6379'
    expose:
      - 6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db-data:
  redis-data:
